### ISSUE TITLE
v0.3.2 breaks page-object gem.

### ISSUE THREAD

**Issue by kapoorlakshya** [titusfortner/watigiri#5]
```
#<NoMethodError: undefined method `name' for #<Watigiri::Element:0x0000000a9daee0>>
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:1066:in `instance_eval'

        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/locators/element/locator.rb:171:in `block in filter_elements_by_regex'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/locators/element/locator.rb:171:in `each'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/locators/element/locator.rb:171:in `find'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/locators/element/locator.rb:171:in `filter_elements_by_regex'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/locators/element/locator.rb:159:in `wd_find_by_regexp_selector'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/locators/element/locator.rb:93:in `using_watir'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watigiri-0.3.2/lib/watigiri/locators/element/locator.rb:25:in `locate'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/elements/element.rb:593:in `locate'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/elements/element.rb:575:in `assert_exists'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/elements/element.rb:50:in `exists?'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/elements/element.rb:514:in `wait_for_exists'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/elements/element.rb:553:in `wait_for_writable'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/elements/element.rb:657:in `element_call'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/watir-6.10.3/lib/watir/user_editable.rb:11:in `set'
        (eval):1:in `process_watir_call'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:1066:in `instance_eval'

        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:1066:in `process_watir_call'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/page-object-2.2.4/lib/page-object/platforms/watir/page_object.rb:215:in `text_field_value_set'
        I:/Opt/Ruby/Ruby223x64/lib/ruby/gems/2.3.0/gems/page-object-2.2.4/lib/page-object/accessors.rb:203:in `block in text_field'
```

@titusfortner - v0.3.1 works fine. I believe this is related to https://github.com/watir/watir/issues/727 and commit 8283ade8bb50fb1b949066b02893f2d6b7f0b58b.

**Comment by titusfortner** [comment]
hmmm, 0.3.1 with watir 6.10 or 6.11 beta?

**Comment by kapoorlakshya** [comment]
Watir 6.10.x

**Comment by titusfortner** [comment]
I figured out the fix to this and a bunch of other issues not yet reported! 

Except it relies on DocumentFragment, which is broken (https://github.com/sparklemotion/nokogiri/issues/572). So I need to figure out another approach.

**Comment by titusfortner** [comment]
0.4.0 should fix all these things now

**Comment by kapoorlakshya** [comment]
Awesome! Thanks!
